int isArmstrong(int x);
int isPalindrome(int x);
int isPrime(int x);
int isStrong(int x);
int isPalindromeRec(int x);
int HelpisPalindrome(int x , int ReverseNum );
int isArmstrongRec(int x);
int Help1isArmstrong(int x, int);
int Help2isArmstrong(int x, int );
int FindTheDigitsNumRec(int x);